<!doctype html>
<html>
<head>
<meta charset="utf-8">
<style>
body{font-family: DejaVu Sans, sans-serif; font-size: 12px;}
.table{width:100%; border-collapse: collapse;}
.table th,.table td{border:1px solid #ccc; padding:6px;}
.text-right{text-align:right}
.text-center{text-align:center}
h2{margin:0 0 10px 0;}
.small{color:#666}
</style>
</head>
<body>
  <h2>Invoice {{ $invoice->invoice_number }}</h2>
  <table style="width:100%; margin-bottom:10px">
    <tr>
      <td>
        <strong>Client:</strong> {{ $invoice->client->name }}<br>
        {{ $invoice->client->email }}<br>
        {{ $invoice->client->phone }}<br>
        {{ $invoice->client->address }}
      </td>
      <td class="text-right">
        <strong>Invoice Date:</strong> {{ $invoice->invoice_date }}<br>
        <strong>Due Date:</strong> {{ $invoice->due_date }}<br>
        <strong>Total:</strong> {{ number_format($invoice->total_amount,2) }}
      </td>
    </tr>
  </table>
  <table class="table">
    <thead><tr><th>Description</th><th class="text-right">Qty</th><th class="text-right">Unit Price</th><th class="text-right">Total</th></tr></thead>
    <tbody>
      @foreach($invoice->items as $it)
      <tr>
        <td>{{ $it->description }}</td>
        <td class="text-right">{{ $it->quantity }}</td>
        <td class="text-right">{{ number_format($it->unit_price,2) }}</td>
        <td class="text-right">{{ number_format($it->total,2) }}</td>
      </tr>
      @endforeach
    </tbody>
    <tfoot>
      <tr><th colspan="3" class="text-right">Grand Total</th><th class="text-right">{{ number_format($invoice->total_amount,2) }}</th></tr>
    </tfoot>
  </table>
  <p class="small">Generated by InvoiceApp</p>
</body>
</html>
